spring:
  profiles:
    active: mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-bean-definition-overriding: true
server:
  port: 8888
  servlet:
    context-path: /uploadProject
mybatis:
  mapper-locations:
    - classpath:mapper/*Mapper.xml
# 上传的文件到的路径
pan:
#  uploadDir: D:\projects
  uploadDir: /data/upload/
---
debug: true
#spring:
#  profiles: oracle
#  datasource:
#    driver-class-name: oracle.jdbc.OracleDriver
#    password: APP_CDT
#    username: APP_CDT
#    url:
---
spring:
  profiles: mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    username: root
    url:
